.ORIG x3000
LEA R6, LETRS
LD R5 ASCIICASE
CHECKLETTER
LDR R0, R6, #0 ; LOADS R6+ OFFSET TO R0
BRZ STRINGDONE ; IF ZERO TERMINATES

ADD R6, R6, #1 ; INCREMENTS INDEX BY 1
ADD R0, R5, R0
BRP LOWERCASE
BR CHECKLETTER ;LOOPS TO TOP

LETRS .stringz "aAaAbTK"
ASCIICASE .FILL #-96

LOWERCASE
    ADD R3, R3, #1
    BR CHECKLETTER
STRINGDONE
    HALT   
    .END